### ISSUE TITLE
using ssh/config gives no such method error

### ISSUE THREAD

**Issue by nskvortsov** [nskvortsov/deployer#18]
[Step 2/2] java.lang.NoSuchMethodError: com.jcraft.jsch.Util.fromFile(Ljava/lang/String;)[B
	at com.jcraft.jsch.OpenSSHConfig.parseFile(OpenSSHConfig.java:97)
	at jetbrains.buildServer.deployer.agent.ssh.SSHSessionProvider.iniSessionSSHConfig(SSHSessionProvider.java:85)
	at jetbrains.buildServer.deployer.agent.ssh.SSHSessionProvider.<init>(SSHSessionProvider.java:65)
	at jetbrains.buildServer.deployer.agent.ssh.SSHDeployerRunner.getDeployerProcess(SSHDeployerRunner.java:44)

----------------------------------------
- Bitbucket: https://bitbucket.org/nskvortsov/deployer/issue/18
- Originally reported by: [mlake900](http://bitbucket.org/mlake900)
- Originally created at: 2013-08-01T19:03:24.453

**Comment by nskvortsov** [comment]
thanks for reporting the error.
Could you attach teamcity-agent.log file from build agent where this failure occured?

Do you have any other custom plugins installed?

----------------------------------------
Original comment by: Nikita Skvortsov

**Comment by nskvortsov** [comment]
hey - so I can't really give out our teamcity-agent.log file, but I do see some other versions of the jsch library. Not exactly sure what takes precedence in the class loading system. 

lake@sage:/home/buildagent/buildagent$ find . | grep jsch
./tools/idea/lib/jsch-0.1.49.jar
./plugins/jetbrains.git/lib/jsch-0.1.44.jar
./plugins/artifactDeployer/lib/jsch-0.1.50.jar
./plugins/ant/lib/ant-jsch.jar


----------------------------------------
Original comment by: [mlake900](http://bitbucket.org/mlake900)

**Comment by nskvortsov** [comment]
So far I can't reproduce the issue. What version of TeamCIty do you use?

----------------------------------------
Original comment by: Nikita Skvortsov

**Comment by nskvortsov** [comment]
Fixed in build teamcity.jetbrains.com/viewLog.html?buildId=87827

----------------------------------------
Original comment by: Nikita Skvortsov

**Comment by nskvortsov** [comment]
Thank you for reporting. Please, update

----------------------------------------
Original comment by: Nikita Skvortsov
