### ISSUE TITLE
Out of Memory Exception

### ISSUE THREAD

**Issue by nskvortsov** [nskvortsov/deployer#20]
I'm consistently getting a Java out of memory exception when trying to copy zip files around 15 MB using the SMB Deployer. 

I've set the wrapper.java.maxmemory property in the wrapper.conf of the agent to 900MB, it had previously set to the default (64). This did not seem to make a difference. 

Let me know if there is any more information i can provide.

Stack:
[Step 2/2] Failed to start build runner 'smb-deploy-runner'
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Unknown Source)
	at jcifs.UniAddress.lookupServerOrWorkgroup(UniAddress.java:173)
	at jcifs.UniAddress.getAllByName(UniAddress.java:290)
	at jcifs.UniAddress.getByName(UniAddress.java:245)
	at jcifs.smb.Dfs.getTrustedDomains(Dfs.java:62)
	at jcifs.smb.Dfs.resolve(Dfs.java:167)
	at jcifs.smb.SmbFile.resolveDfs(SmbFile.java:671)
	at jcifs.smb.SmbFile.send(SmbFile.java:773)
	at jcifs.smb.SmbFileOutputStream.writeDirect(SmbFileOutputStream.java:245)
	at jcifs.smb.SmbFileOutputStream.write(SmbFileOutputStream.java:216)
	at jetbrains.buildServer.util.TCStreamUtil.writeBinary(TCStreamUtil.java:103)
	at jetbrains.buildServer.util.TCStreamUtil.writeBinary(TCStreamUtil.java:89)
	at jetbrains.buildServer.util.FileUtil.copyStreams(FileUtil.java:469)
	at jetbrains.buildServer.util.FileUtil.copy(FileUtil.java:1316)
	at jetbrains.buildServer.deployer.agent.smb.SMBBuildProcessAdapter.upload(SMBBuildProcessAdapter.java:117)
	at jetbrains.buildServer.deployer.agent.smb.SMBBuildProcessAdapter.runProcess(SMBBuildProcessAdapter.java:80)
	at jetbrains.buildServer.deployer.agent.SyncBuildProcessAdapter.start(SyncBuildProcessAdapter.java:58)
	at jetbrains.buildServer.agent.impl.buildStages.runnerStages.start.CallRunnerStage.doBuildStage(CallRunnerStage.java:58)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:25)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:18)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor.doStages(RunnerStagesExecutor.java:18)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.callRunnerStages(RunnerContextExecutor.java:43)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.doProcessNextStep(StepExecutor.java:89)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.processNextStep(StepExecutor.java:44)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.doBuildStage(ForEachBuildRunnerStage.java:77)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:31)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.BuildRunAction.doStages(BuildRunAction.java:70)
	at jetbrains.buildServer.agent.impl.BuildRunAction.runBuild(BuildRunAction.java:50)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:247)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:48)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:220)
	at java.lang.Thread.run(Unknown Source)

----------------------------------------
- Bitbucket: https://bitbucket.org/nskvortsov/deployer/issue/20
- Originally reported by: Anonymous
- Originally created at: 2013-09-05T16:15:28.554

**Comment by nskvortsov** [comment]
I submitted this bug wasn't signed in - adding comment for tracking

----------------------------------------
Original comment by: Dan Nash

**Comment by nskvortsov** [comment]
I experience the same problem. Sometimes it works and another time we get an error.

----------------------------------------
Original comment by: [arelium](http://bitbucket.org/arelium)

**Comment by nskvortsov** [comment]
Possible workaround:
based on this JCIFS [mail list thread](https://lists.samba.org/archive/jcifs/2010-February/009082.html) there is a work around to add specific options:

  jcifs.resolveOrder=DNS

  jcifs.smb.client.dfs.disabled=true

to set this options on build agent startup see [this documentation page](http://confluence.jetbrains.com/display/TCD8/Configuring+Build+Agent+Startup+Properties)

----------------------------------------
Original comment by: Nikita Skvortsov

**Comment by nskvortsov** [comment]
I will be out of the office until Monday, December 23 returning Thursday December 26th. I will be checking emails periodically and will get back to you as soon as possible.

----------------------------------------
Original comment by: Dan Nash

**Comment by nskvortsov** [comment]
@dtmnash did you have a chance to try the workaround?

----------------------------------------
Original comment by: Nikita Skvortsov

**Comment by nskvortsov** [comment]
I will be out of the office returning Friday, June 20th through Friday June 29th. I will respond to your email as soon as possible.

----------------------------------------
Original comment by: Dan Nash

**Comment by nskvortsov** [comment]
Yes, it worked!

----------------------------------------
Original comment by: Dan Nash

**Comment by nskvortsov** [comment]
@dtmnash thank you for the followup

----------------------------------------
Original comment by: Nikita Skvortsov

**Comment by nskvortsov** [comment]
So far, this is the limitation of SMB library used in the project. 
The workaround is available, and the fix requires new SMB Java library, which does not seem to be available at the moment.

----------------------------------------
Original comment by: Nikita Skvortsov

**Comment by nskvortsov** [comment]
Hallo, I experience the same problem. What is the workaround ?

----------------------------------------
Original comment by: Jerome Mohanan

**Comment by nskvortsov** [comment]
@nskvortsov responded with the work around. 

Worked great for me!

Possible workaround: based on this JCIFS mail list thread there is a work around to add specific options:
jcifs.resolveOrder=DNS
jcifs.smb.client.dfs.disabled=true
to set this options on build agent startup see this documentation page

----------------------------------------
Original comment by: Dan Nash

**Comment by nskvortsov** [comment]
Added an option on web ui "use DNS only name resolution", which is an equivalent of existing workaround. Implemented in [this build](https://teamcity.jetbrains.com/viewLog.html?buildId=174538&tab=artifacts&buildTypeId=bt402)

----------------------------------------
Original comment by: Nikita Skvortsov
