### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by nskvortsov** [nskvortsov/deployer#24]
ERROR -    jetbrains.buildServer.AGENT - java.lang.NullPointerException
 
jetbrains.buildServer.RunBuildException: java.lang.NullPointerException
	at jetbrains.buildServer.deployer.agent.tomcat.TomcatBuildProcessAdapter.runProcess(TomcatBuildProcessAdapter.java:107)
	at jetbrains.buildServer.deployer.agent.SyncBuildProcessAdapter.start(SyncBuildProcessAdapter.java:58)
	at jetbrains.buildServer.agent.impl.buildStages.runnerStages.start.CallRunnerStage.doBuildStage(CallRunnerStage.java:58)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:25)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:18)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor.doStages(RunnerStagesExecutor.java:18)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.callRunnerStages(RunnerContextExecutor.java:43)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.processNextStep(StepExecutor.java:25)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeRunnerStep(ForEachBuildRunnerStage.java:138)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.runStep(ForEachBuildRunnerStage.java:123)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeBuildRunners(ForEachBuildRunnerStage.java:83)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.doBuildStage(ForEachBuildRunnerStage.java:44)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:31)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.BuildRunAction.doStages(BuildRunAction.java:70)
	at jetbrains.buildServer.agent.impl.BuildRunAction.runBuild(BuildRunAction.java:50)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:248)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:48)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:221)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at org.apache.tools.ant.taskdefs.Redirector.complete(Redirector.java:907)
	at org.apache.catalina.ant.BaseRedirectorHelperTask.closeRedirector(BaseRedirectorHelperTask.java:266)
	at org.apache.catalina.ant.AbstractCatalinaTask.execute(AbstractCatalinaTask.java:271)
	at org.apache.catalina.ant.AbstractCatalinaTask.execute(AbstractCatalinaTask.java:148)
	at org.apache.catalina.ant.ListTask.execute(ListTask.java:51)
	at jetbrains.buildServer.deployer.agent.tomcat.TomcatBuildProcessAdapter.runProcess(TomcatBuildProcessAdapter.java:81)
	... 24 more

----------------------------------------
- Bitbucket: https://bitbucket.org/nskvortsov/deployer/issue/24
- Originally reported by: Kostiantyn Miklevskyi
- Originally created at: 2014-03-07T15:06:38.325

**Comment by nskvortsov** [comment]
https://issues.apache.org/bugzilla/show_bug.cgi?id=50552

Mark Thomas 2011-01-07 06:28:10 UTC
Fixed in 7.0.x for 7.0.6 using Chris S's first proposal.

Konstantin Kolinko 2011-01-08 17:23:10 UTC
Applied the patch to 6.0 in r1056813 and it will be in 6.0.30.

Time to upgrade Tomcat deps.

----------------------------------------
Original comment by: Kostiantyn Miklevskyi

**Comment by nskvortsov** [comment]
That's how I fixed it for myself.

----------------------------------------
Original comment by: Kostiantyn Miklevskyi

**Comment by nskvortsov** [comment]
Duplicate of #8.

----------------------------------------
Original comment by: Nikita Skvortsov
