### ISSUE TITLE
FTP Exception is not informative

### ISSUE THREAD

**Issue by nskvortsov** [nskvortsov/deployer#3]
Original description: 

FTP deployer failed.
If something in the build configuration is wrong, it'd be better make the error a bit more informative :)

Stacktrace:

[20:39:44]Step 2/2: Upload onto FTP (FTP Deployer) (7s)
[20:39:51]
[Step 2/2] it.sauronsoftware.ftp4j.FTPException [code=331, message= null]
it.sauronsoftware.ftp4j.FTPException [code=331, message= null]
        at it.sauronsoftware.ftp4j.FTPClient.login(FTPClient.java:1265)
        at it.sauronsoftware.ftp4j.FTPClient.login(FTPClient.java:1186)
        at jetbrains.buildServer.deployer.agent.ftp.FtpBuildProcessAdapter.start(FtpBuildProcessAdapter.java:87)
        at jetbrains.buildServer.agent.impl.buildStages.runnerStages.start.CallRunnerStage.doBuildStage(CallRunnerStage.java:58)
        at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:25)
        at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:18)
        at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
        at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
        at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor.doStages(RunnerStagesExecutor.java:18)
        at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.callRunnerStages(RunnerContextExecutor.java:43)
        at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.doProcessNextStep(StepExecutor.java:89)
        at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.processNextStep(StepExecutor.java:44)
        at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.doBuildStage(ForEachBuildRunnerStage.java:77)
        at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:31)
        at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)
        at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
        at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
        at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)
        at jetbrains.buildServer.agent.impl.BuildRunAction.doStages(BuildRunAction.java:70)
        at jetbrains.buildServer.agent.impl.BuildRunAction.runBuild(BuildRunAction.java:50)
        at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:247)
        at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:48)
        at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:220)
        at java.lang.Thread.run(Thread.java:636)
[20:39:52][Step 2/2] Step Upload onto FTP (FTP Deployer) failed with unexpected error

----------------------------------------
- Bitbucket: https://bitbucket.org/nskvortsov/deployer/issue/3
- Originally reported by: Nikita Skvortsov
- Originally created at: 2012-11-22T08:50:37.055

**Comment by nskvortsov** [comment]
Stack traces are removed from Build Logs,

Also added validators on the UI, made code far more stable

----------------------------------------
Original comment by: Nikita Skvortsov
