### ISSUE TITLE
SSH Deployer runner hangs

### ISSUE THREAD

**Issue by nskvortsov** [nskvortsov/deployer#30]
Do you know what could be the reason of hanging of an agent running SSH Deployer task with SCP? 
It doesn't even respond to "Stop task".

----------------------------------------
- Bitbucket: https://bitbucket.org/nskvortsov/deployer/issue/30
- Originally reported by: Denis Mikhaylov
- Originally created at: 2014-07-01T16:24:14.697

**Comment by nskvortsov** [comment]
It is hard to tell without additional info.
I need to take a look at thread dumps of build agent's java process.

Please, reproduce the problem, then take several thread dumps (use [this instruction](http://confluence.jetbrains.com/display/TCD8/Reporting+Issues#ReportingIssues-AgentThreadDump)) in short interval and attach them here.

----------------------------------------
Original comment by: Nikita Skvortsov

**Comment by nskvortsov** [comment]
Attaching to process ID 7111, please wait...
Debugger attached successfully.
Server compiler detected.
JVM version is 24.60-b09
Deadlock Detection:

java.lang.RuntimeException: Unable to deduce type of thread from address 0x00000000039ae800 (expected type JavaThread, CompilerThread, ServiceThread, JvmtiAgentThread, or SurrogateLockerThread)
	at sun.jvm.hotspot.runtime.Threads.createJavaThreadWrapper(Threads.java:162)
	at sun.jvm.hotspot.runtime.Threads.first(Threads.java:150)
	at sun.jvm.hotspot.runtime.DeadlockDetector.createThreadTable(DeadlockDetector.java:149)
	at sun.jvm.hotspot.runtime.DeadlockDetector.print(DeadlockDetector.java:56)
	at sun.jvm.hotspot.runtime.DeadlockDetector.print(DeadlockDetector.java:39)
	at sun.jvm.hotspot.tools.StackTrace.run(StackTrace.java:52)
	at sun.jvm.hotspot.tools.StackTrace.run(StackTrace.java:45)
	at sun.jvm.hotspot.tools.JStack.run(JStack.java:60)
	at sun.jvm.hotspot.tools.Tool.start(Tool.java:221)
	at sun.jvm.hotspot.tools.JStack.main(JStack.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at sun.tools.jstack.JStack.runJStackTool(JStack.java:136)
	at sun.tools.jstack.JStack.main(JStack.java:102)
Caused by: sun.jvm.hotspot.types.WrongTypeException: No suitable match for type of address 0x00000000039ae800
	at sun.jvm.hotspot.runtime.InstanceConstructor.newWrongTypeException(InstanceConstructor.java:62)
	at sun.jvm.hotspot.runtime.VirtualConstructor.instantiateWrapperFor(VirtualConstructor.java:80)
	at sun.jvm.hotspot.runtime.Threads.createJavaThreadWrapper(Threads.java:158)
	... 15 more
Can't print deadlocks:Unable to deduce type of thread from address 0x00000000039ae800 (expected type JavaThread, CompilerThread, ServiceThread, JvmtiAgentThread, or SurrogateLockerThread)
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at sun.tools.jstack.JStack.runJStackTool(JStack.java:136)
	at sun.tools.jstack.JStack.main(JStack.java:102)
Caused by: java.lang.RuntimeException: Unable to deduce type of thread from address 0x00000000039ae800 (expected type JavaThread, CompilerThread, ServiceThread, JvmtiAgentThread, or SurrogateLockerThread)
	at sun.jvm.hotspot.runtime.Threads.createJavaThreadWrapper(Threads.java:162)
	at sun.jvm.hotspot.runtime.Threads.first(Threads.java:150)
	at sun.jvm.hotspot.tools.StackTrace.run(StackTrace.java:65)
	at sun.jvm.hotspot.tools.StackTrace.run(StackTrace.java:45)
	at sun.jvm.hotspot.tools.JStack.run(JStack.java:60)
	at sun.jvm.hotspot.tools.Tool.start(Tool.java:221)
	at sun.jvm.hotspot.tools.JStack.main(JStack.java:86)
	... 6 more
Caused by: sun.jvm.hotspot.types.WrongTypeException: No suitable match for type of address 0x00000000039ae800
	at sun.jvm.hotspot.runtime.InstanceConstructor.newWrongTypeException(InstanceConstructor.java:62)
	at sun.jvm.hotspot.runtime.VirtualConstructor.instantiateWrapperFor(VirtualConstructor.java:80)
	at sun.jvm.hotspot.runtime.Threads.createJavaThreadWrapper(Threads.java:158)
	... 12 more


----------------------------------------
Original comment by: Denis Mikhaylov

**Comment by nskvortsov** [comment]
@denis-mikhaylov wow. That's really does not look like the thread dump.

What OS are you running? What JDK version? If it's openjdk, it has some issues with thread dumps: [first](https://bugzilla.redhat.com/show_bug.cgi?id=1095504) and [second](https://bugzilla.redhat.com/show_bug.cgi?id=1010786) , Both issues has workarounds.

Please, try these workarounds (if applicable) and attach resulting stacktrace here.

----------------------------------------
Original comment by: Nikita Skvortsov

**Comment by nskvortsov** [comment]
Possibly related to #34

Try using [this build](http://teamcity.jetbrains.com/repository/download/bt402/147195:id/deploy-runner.zip)

----------------------------------------
Original comment by: Nikita Skvortsov

**Comment by nskvortsov** [comment]
@denis-mikhaylov did you have a chance to try new build or to collect a stacktrace?

----------------------------------------
Original comment by: Nikita Skvortsov

**Comment by nskvortsov** [comment]
No responce from reporter.

----------------------------------------
Original comment by: Nikita Skvortsov
