### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by nskvortsov** [nskvortsov/deployer#32]
(TeamCity Professional 8.1.3 (build 30101))
When I'm running Cargo deploy I'm getting the following exception:
```
INFO   | jvm 1    | 2014/07/17 10:41:22 | jetbrains.buildServer.RunBuildException: org.codehaus.cargo.container.ContainerException: Failed to create deployable with implementation class org.codehaus.cargo.container.tomcat.TomcatWAR for the parameters (container [id = [tomcat7x]], deployable type [war]). 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at jetbrains.buildServer.deployer.agent.cargo.CargoBuildProcessAdapter.runProcess(CargoBuildProcessAdapter.java:104) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at jetbrains.buildServer.deployer.agent.SyncBuildProcessAdapter.start(SyncBuildProcessAdapter.java:58) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at jetbrains.buildServer.agent.impl.buildStages.runnerStages.start.CallRunnerStage.doBuildStage(CallRunnerStage.java:58) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:25) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:18) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor.doStages(RunnerStagesExecutor.java:18) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.callRunnerStages(RunnerContextExecutor.java:43) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.processNextStep(StepExecutor.java:25) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeRunnerStep(ForEachBuildRunnerStage.java:138) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.runStep(ForEachBuildRunnerStage.java:123) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeBuildRunners(ForEachBuildRunnerStage.java:83) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.doBuildStage(ForEachBuildRunnerStage.java:44) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:31) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at jetbrains.buildServer.agent.impl.BuildRunAction.doStages(BuildRunAction.java:70) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at jetbrains.buildServer.agent.impl.BuildRunAction.runBuild(BuildRunAction.java:50) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:265) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:52) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:231) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at java.lang.Thread.run(Thread.java:744) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | Caused by: org.codehaus.cargo.container.ContainerException: Failed to create deployable with implementation class org.codehaus.cargo.container.tomcat.TomcatWAR for the parameters (container [id = [tomcat7x]], deployable type [war]). 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at org.codehaus.cargo.generic.spi.AbstractGenericHintFactory.createImplementation(AbstractGenericHintFactory.java:154) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at org.codehaus.cargo.generic.spi.AbstractIntrospectionGenericHintFactory.createImplementation(AbstractIntrospectionGenericHintFactory.java:93) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at org.codehaus.cargo.generic.deployable.DefaultDeployableFactory.createDeployable(DefaultDeployableFactory.java:156) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at jetbrains.buildServer.deployer.agent.cargo.CargoBuildProcessAdapter.runProcess(CargoBuildProcessAdapter.java:93) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	... 24 more 
INFO   | jvm 1    | 2014/07/17 10:41:22 | Caused by: java.lang.reflect.InvocationTargetException 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:526) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at org.codehaus.cargo.generic.deployable.DefaultDeployableFactory.createInstance(DefaultDeployableFactory.java:196) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at org.codehaus.cargo.generic.deployable.DefaultDeployableFactory.createInstance(DefaultDeployableFactory.java:47) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at org.codehaus.cargo.generic.spi.AbstractGenericHintFactory.createImplementation(AbstractGenericHintFactory.java:150) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	... 27 more 
INFO   | jvm 1    | 2014/07/17 10:41:22 | Caused by: java.lang.ExceptionInInitializerError 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at org.codehaus.cargo.module.webapp.tomcat.TomcatContextXmlIo.<init>(TomcatContextXmlIo.java:40) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at org.codehaus.cargo.module.webapp.tomcat.TomcatContextXmlIo.parseTomcatConfigXml(TomcatContextXmlIo.java:54) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at org.codehaus.cargo.module.webapp.tomcat.TomcatWarArchive.parseTomcatContextXml(TomcatWarArchive.java:92) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at org.codehaus.cargo.module.webapp.tomcat.TomcatWarArchive.<init>(TomcatWarArchive.java:59) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at org.codehaus.cargo.container.tomcat.TomcatWAR.<init>(TomcatWAR.java:50) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	... 34 more 
INFO   | jvm 1    | 2014/07/17 10:41:22 | Caused by: java.lang.ClassCastException: org.apache.xerces.jaxp.SAXParserFactoryImpl cannot be cast to javax.xml.parsers.SAXParserFactory 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at javax.xml.parsers.SAXParserFactory.newInstance(Unknown Source) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at org.codehaus.cargo.module.Dtd.<init>(Dtd.java:144) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at org.codehaus.cargo.module.webapp.tomcat.TomcatContextXmlType.<init>(TomcatContextXmlType.java:52) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	at org.codehaus.cargo.module.webapp.tomcat.TomcatContextXmlType.<clinit>(TomcatContextXmlType.java:34) 
INFO   | jvm 1    | 2014/07/17 10:41:22 | 	... 39 more
```

----------------------------------------
- Bitbucket: https://bitbucket.org/nskvortsov/deployer/issue/32
- Originally reported by: [tyutyutyu](http://bitbucket.org/tyutyutyu)
- Originally created at: 2014-07-17T14:42:18.771

**Comment by nskvortsov** [comment]
Issue #37 was marked as a duplicate of this issue.

----------------------------------------
Original comment by: Nikita Skvortsov

**Comment by nskvortsov** [comment]
Fixed in [this build](http://teamcity.jetbrains.com/viewLog.html?buildId=156111)

----------------------------------------
Original comment by: Nikita Skvortsov
