### ISSUE TITLE
FTP Deployer issue

### ISSUE THREAD

**Issue by nskvortsov** [nskvortsov/deployer#43]
Unexpected error: java.lang.RuntimeException: Listener class class jetbrains.buildServer.agent.impl.artifacts.ArtifactsBuilderAdapter does not contain any non-empty event listening method implementations. Check there are some overridden methods or this class is not annotated with interface jetbrains.buildServer.util.EventListenerAdapter.

----------------------------------------
- Bitbucket: https://bitbucket.org/nskvortsov/deployer/issue/43
- Originally reported by: Anonymous
- Originally created at: 2014-09-19T09:06:04.364

**Comment by nskvortsov** [comment]
Please attach following information:

1. Build Log
2. teamcity-agent.log file
3. TeamCity version

----------------------------------------
Original comment by: Nikita Skvortsov

**Comment by nskvortsov** [comment]
1. [Build Log](https://www.dropbox.com/s/x1zuyehe6wvirce/teamcity-build.log?dl=0)
2. [teamcity-agent.log](https://www.dropbox.com/s/cdbevmdzzkzh2ws/teamcity-agent.log?dl=0)
3. 7.0 (build 21241)

It is perfect plug in for me I would be grateful for your help.
I tried to use FTP Connector and SSH Connector however the exception is always the same.

----------------------------------------
Original comment by: Jerzy Pietruszewski

**Comment by nskvortsov** [comment]
WARN - nt.impl.BuildExceptionsHandler - Failed to execute runner stage: CallRunnerStage. Listener class class jetbrains.buildServer.agent.impl.artifacts.ArtifactsBuilderAdapter does not contain any non-empty event listening method implementations. Check there are some overridden methods or this class is not annotated with interface jetbrains.buildServer.util.EventListenerAdapter. 
jetbrains.buildServer.agent.impl.buildStages.RunnerStageExecutionException: Listener class class jetbrains.buildServer.agent.impl.artifacts.ArtifactsBuilderAdapter does not contain any non-empty event listening method implementations. Check there are some overridden methods or this class is not annotated with interface jetbrains.buildServer.util.EventListenerAdapter.
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:27)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:18)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:76)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:36)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor.doStages(RunnerStagesExecutor.java:18)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.RunnerContextExecutor.callRunnerStages(RunnerContextExecutor.java:40)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.ForEachBuildRunnerStage.doBuildStage(ForEachBuildRunnerStage.java:68)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:31)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:76)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:36)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.BuildRunAction.doStages(BuildRunAction.java:70)
	at jetbrains.buildServer.agent.impl.BuildRunAction.runBuild(BuildRunAction.java:50)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:242)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:47)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:215)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.RuntimeException: Listener class class jetbrains.buildServer.agent.impl.artifacts.ArtifactsBuilderAdapter does not contain any non-empty event listening method implementations. Check there are some overridden methods or this class is not annotated with interface jetbrains.buildServer.util.EventListenerAdapter.
	at jetbrains.buildServer.util.EventDispatcherHandlers.registerListener(EventDispatcherHandlers.java:76)
	at jetbrains.buildServer.util.EventDispatcherHandlers.addListener(EventDispatcherHandlers.java:55)
	at jetbrains.buildServer.util.EventDispatcher.addListener(EventDispatcher.java:138)
	at jetbrains.buildServer.agent.impl.artifacts.ArtifactsBuilder.addListener(ArtifactsBuilder.java:33)
	at jetbrains.buildServer.deployer.agent.base.BaseDeployerRunner.createBuildProcess(BaseDeployerRunner.java:47)
	at jetbrains.buildServer.agent.impl.runner.CallRunnerService.createBuildProcess(CallRunnerService.java:40)
	at jetbrains.buildServer.agent.impl.buildStages.runnerStages.start.CallRunnerStage.doBuildStage(CallRunnerStage.java:45)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:25)
	... 17 more


----------------------------------------
Original comment by: Jerzy Pietruszewski

**Comment by nskvortsov** [comment]
Any progress with that bug?

----------------------------------------
Original comment by: Jerzy Pietruszewski

**Comment by nskvortsov** [comment]
Nikita are you going to fix this?

----------------------------------------
Original comment by: Jerzy Pietruszewski

**Comment by nskvortsov** [comment]
fix issue #43 restore 7.0 compatibility


→ <<cset 896797eadf67>>

----------------------------------------
Original comment by: Nikita Skvortsov

**Comment by nskvortsov** [comment]
@jpietruszewski please try this build: http://teamcity.jetbrains.com/guestAuth/repository/download/bt402/169041:id/deploy-runner.zip?guest=1 


----------------------------------------
Original comment by: Nikita Skvortsov
