### ISSUE TITLE
SMB deployer attempts to copy artifacts to top level of host, rather than share/subdir

### ISSUE THREAD

**Issue by nskvortsov** [nskvortsov/deployer#5]
Unable to get SMB deployment to work. After enabling debug logging on the build agent, it appears from the log output that the plugin is not constructing the destination path correctly. It seems as though the plugin is attempting to copy the artifacts to the root of the SMB host, rather than to the host/share/subdir path.

Below is an excerpt from the log output -- note that the "target" output below looks correct, but the "destDirectory" and "destFile" files look incorrect.

[2013-01-08 20:57:47,786]  DEBUG -    jetbrains.buildServer.AGENT - Trying to connect with following parameters:
username=[myuser]
password=[mypassword]
domain=[MYDOMAIN]
target=[smb://myhost/myshare/mysubdir/] 
[2013-01-08 20:57:47,787]  DEBUG -    jetbrains.buildServer.AGENT - Uploading source=[C:\ProgramData\JetBrains\TeamCity\BuildAgent\work\c1cbabd2fbe1f943\myartifact.txt] to 
destDirectory=[smb://myhost/] destFile=[smb://myhost/myartifact.txt] 
[2013-01-08 20:57:47,826]  ERROR -    jetbrains.buildServer.AGENT - Trying to connect with following parameters:
username=[myuser]
password=[mypassword]
domain=[MYDOMAIN]
target=[smb://myhost/myshare/mysubdir/] 
jcifs.smb.SmbException: The network name cannot be found.
	at jcifs.smb.SmbTransport.checkStatus(SmbTransport.java:563)
	at jcifs.smb.SmbTransport.send(SmbTransport.java:663)
	at jcifs.smb.SmbSession.send(SmbSession.java:238)
	at jcifs.smb.SmbTree.treeConnect(SmbTree.java:176)
	at jcifs.smb.SmbFile.doConnect(SmbFile.java:911)
	at jcifs.smb.SmbFile.connect(SmbFile.java:954)
	at jcifs.smb.SmbFile.connect0(SmbFile.java:880)
	at jcifs.smb.SmbFile.open0(SmbFile.java:972)
	at jcifs.smb.SmbFile.open(SmbFile.java:1006)
	at jcifs.smb.SmbFileOutputStream.<init>(SmbFileOutputStream.java:142)
	at jcifs.smb.SmbFileOutputStream.<init>(SmbFileOutputStream.java:97)
	at jcifs.smb.SmbFileOutputStream.<init>(SmbFileOutputStream.java:67)
	at jcifs.smb.SmbFile.getOutputStream(SmbFile.java:2853)
	at jetbrains.buildServer.deployer.agent.smb.SMBBuildProcessAdapter.upload(SMBBuildProcessAdapter.java:131)

----------------------------------------
- Bitbucket: https://bitbucket.org/nskvortsov/deployer/issue/5
- Originally reported by: Matt B
- Originally created at: 2013-01-08T23:47:30.110

**Comment by nskvortsov** [comment]
Fixed in [this build](http://teamcity.jetbrains.com/viewLog.html?buildId=77548&tab=buildResultsDiv&buildTypeId=bt402&guest=1) Please, update the plugin

----------------------------------------
Original comment by: Nikita Skvortsov

**Comment by nskvortsov** [comment]
Thanks!

----------------------------------------
Original comment by: Matt B

**Comment by nskvortsov** [comment]
"Build with id '77548' not found."  Can you please share latest jar for jcifs [currently I'm using jcifs-1.3.17.jar]

Getting same exception:
  [ accessing.. : smb://mydomain;userid:pswd@mydomain.com/data1/test1/folder1/hello.txt ]

jcifs.smb.SmbException: The network name cannot be found.
	at jcifs.smb.SmbTransport.checkStatus(SmbTransport.java:563)
	at jcifs.smb.SmbTransport.send(SmbTransport.java:663)
	at jcifs.smb.SmbSession.send(SmbSession.java:238)
	at jcifs.smb.SmbTree.treeConnect(SmbTree.java:176)
	at jcifs.smb.SmbFile.doConnect(SmbFile.java:911)
	at jcifs.smb.SmbFile.connect(SmbFile.java:954)
	at jcifs.smb.SmbFile.connect0(SmbFile.java:880)
	at jcifs.smb.SmbFile.open0(SmbFile.java:972)
	at jcifs.smb.SmbFile.open(SmbFile.java:1006)
	at jcifs.smb.SmbFileInputStream.<init>(SmbFileInputStream.java:73)
	at jcifs.smb.SmbFileInputStream.<init>(SmbFileInputStream.java:65)
	at com.test.TestMerge.readFile(TestMerge.java:111)
	at com.test.TestMerge.combinePDFs(TestMerge.java:82)
	at com.test.TestMerge.main(TestMerge.java:35)

----------------------------------------
Original comment by: [pmsafvan](http://bitbucket.org/pmsafvan)
