### ISSUE TITLE
IOException error during SSH Deployer

### ISSUE THREAD

**Issue by nskvortsov** [nskvortsov/deployer#7]
I configured build with Configuration Parameter and SSH Deployer step and I'm getting this error

```
#!java

java.io.IOException: scp: error: unexpected filename: //

	at jetbrains.buildServer.deployer.agent.ssh.scp.ScpExecUtil.checkScpAck(ScpExecUtil.java:25)
	at jetbrains.buildServer.deployer.agent.ssh.scp.DirScpOperation.execute(DirScpOperation.java:54)
	at jetbrains.buildServer.deployer.agent.ssh.scp.ScpProcessAdapter.createRemotePath(ScpProcessAdapter.java:182)
	at jetbrains.buildServer.deployer.agent.ssh.scp.ScpProcessAdapter.start(ScpProcessAdapter.java:142)
	at jetbrains.buildServer.agent.impl.buildStages.runnerStages.start.CallRunnerStage.doBuildStage(CallRunnerStage.java:58)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:25)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:18)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor.doStages(RunnerStagesExecutor.java:18)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.callRunnerStages(RunnerContextExecutor.java:43)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.doProcessNextStep(StepExecutor.java:89)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.processNextStep(StepExecutor.java:44)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.doBuildStage(ForEachBuildRunnerStage.java:77)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:31)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.BuildRunAction.doStages(BuildRunAction.java:70)
	at jetbrains.buildServer.agent.impl.BuildRunAction.runBuild(BuildRunAction.java:50)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:247)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:48)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:220)
```

My config:
Target: %Environment%:/opt/sec/
Artifact path: services/**/target/*.jar => deploy

SCP, Port 22, username and password

Everything works fine when I remove directory(:/opt/sec) from Target.

Is it a problem with my configuration or bug in the Deployer?

----------------------------------------
- Bitbucket: https://bitbucket.org/nskvortsov/deployer/issue/7
- Originally reported by: Anonymous
- Originally created at: 2013-02-13T13:18:15.472

**Comment by nskvortsov** [comment]
This issue was reported http://youtrack.jetbrains.com/issue/TW-25013 and is supposed to be fixed in this build of plugin: http://teamcity.jetbrains.com/viewLog.html?buildId=73940&tab=buildResultsDiv&buildTypeId=bt402


Please, try updating plugin to the latest available version

----------------------------------------
Original comment by: Nikita Skvortsov

**Comment by nskvortsov** [comment]
Possible duplicate of http://youtrack.jetbrains.com/issue/TW-25013

----------------------------------------
Original comment by: Nikita Skvortsov

**Comment by nskvortsov** [comment]
I'm running the latest version (straight from the repo) and the problem still occurs. 

Btw, I'm not authorized to access TW-25013.

EDIT: I checked both versions (build from the sources and one from the link) and problem is still there.

----------------------------------------
Original comment by: Błażej Bucko

**Comment by nskvortsov** [comment]
Thank you, I will look into it

----------------------------------------
Original comment by: Nikita Skvortsov

**Comment by nskvortsov** [comment]
@bbucko as a workaround, can you try to remove /opt/sec from "Target" and add it to "Artifacts path" like this:

services/\**/target/\*.jar => /opt/sec/deploy

----------------------------------------
Original comment by: Nikita Skvortsov

**Comment by nskvortsov** [comment]
Still no-go. Instead of /opt/sec/deploy artifacts are deployed into ~//opt/sec/deploy.

----------------------------------------
Original comment by: Błażej Bucko

**Comment by nskvortsov** [comment]
@bbucko I have nailed the problem, but it will take some time to fix it properly. Another possible workaround is changing Transport type from SCP to SFTP (SFTP is not relevant to standart FTP in any manner and works well with openssh server)

----------------------------------------
Original comment by: Nikita Skvortsov

**Comment by nskvortsov** [comment]
Fixed in this build: http://teamcity.jetbrains.com/viewLog.html?buildId=77510&tab=buildResultsDiv&buildTypeId=bt402

----------------------------------------
Original comment by: Nikita Skvortsov
