### ISSUE TITLE
FTP deployer fails on existing target directory

### ISSUE THREAD

**Issue by nskvortsov** [nskvortsov/deployer#9]
When the target directory already exists FTP deployer throws an exception
resulting in the stacktrace below:

[12:16:28]
[Step 3/4] it.sauronsoftware.ftp4j.FTPException [code=521, message= "/home/ideeadm8/tmp" directory exists]
it.sauronsoftware.ftp4j.FTPException [code=521, message= "/home/ideeadm8/tmp" directory exists]
	at it.sauronsoftware.ftp4j.FTPClient.createDirectory(FTPClient.java:1934)
	at jetbrains.buildServer.deployer.agent.ftp.FtpBuildProcessAdapter.createDirSkipExisting(FtpBuildProcessAdapter.java:148)
	at jetbrains.buildServer.deployer.agent.ftp.FtpBuildProcessAdapter.createPath(FtpBuildProcessAdapter.java:139)
	at jetbrains.buildServer.deployer.agent.ftp.FtpBuildProcessAdapter.start(FtpBuildProcessAdapter.java:107)
	at jetbrains.buildServer.agent.impl.buildStages.runnerStages.start.CallRunnerStage.doBuildStage(CallRunnerStage.java:58)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:25)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:18)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor.doStages(RunnerStagesExecutor.java:18)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.callRunnerStages(RunnerContextExecutor.java:43)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.doProcessNextStep(StepExecutor.java:89)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.processNextStep(StepExecutor.java:44)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.doBuildStage(ForEachBuildRunnerStage.java:77)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:31)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.BuildRunAction.doStages(BuildRunAction.java:70)
	at jetbrains.buildServer.agent.impl.BuildRunAction.runBuild(BuildRunAction.java:50)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:243)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:48)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:216)
	at java.lang.Thread.run(Thread.java:662)
[12:16:28][Step 3/4] Step FTP test (FTP Deployer) failed with unexpected error

----------------------------------------
- Bitbucket: https://bitbucket.org/nskvortsov/deployer/issue/9
- Originally reported by: Christian Schmitt
- Originally created at: 2013-02-26T12:18:18.765

**Comment by nskvortsov** [comment]
Fixed in this [build](http://teamcity.jetbrains.com/viewLog.html?buildId=78311&tab=buildResultsDiv&buildTypeId=bt402&guest=1)

----------------------------------------
Original comment by: Nikita Skvortsov

**Comment by nskvortsov** [comment]
Works.

Thanks!

----------------------------------------
Original comment by: Christian Schmitt
